---
name: OpenAI Code Review
"on":
  pull_request:
    types: [opened, synchronize]
jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: ChatGPT explain code
        uses: cirolini/chatgpt-github-actions@v1
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "text-davinci-002"
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: patch
